services:
  - type: web
    name: repartly-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DATABASE_URL
        value: mysql://u960928938_rootrepartly:Ew_Mhn5Swk6$Ybc@193.203.168.99:3306/u960928938_repartly
