services:
  - type: web
    name: repartly-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DATABASE_URL
        sync: false  
