# Generated by Django 5.2.1 on 2025-05-11 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recogida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recogidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
