# Generated by Django 5.2.1 on 2025-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_entrega_gasto_recogida'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nif',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
